### ISSUE TITLE
Ensure lessons show current source code.

### ISSUE THREAD

**Issue by ibgreen** [philogb/philogl#44]
@wwwtyro, lessons show old gists instead of latest refactored source.

**Comment by wwwtyro** [comment]
@ibgreen I'll fix it. It turned out to be not a small fix; the current scheme points to a gist that is a script that inserts the already-formatted code snippet into the page. I think there's a couple options to fix this:

1. Ask for the original code that performed the compiling to the gists and redo all the things.
2. Just redo it.

I prefer option 2 because I'd like to 1) modernize the appearance of the lessons and 2) do away with the need to have another (possibly manual because of interacting with gist?) build step - I can build the functionality into a single common script shared across the lessons. I expect it to take a single evening, and we'd have a really nice-looking lesson interface at the end.

**Comment by ibgreen** [comment]
Just a question... Do we need to generate gists？Can't we just have the page load its source code using an Ajax request, just like it loads shaders and other resources? and Isn't there some npm 'code editor' component that formats JavaScript?

Alternatively, we could use github links to the files and embed in iframes?

**Comment by ibgreen** [comment]
http://stackoverflow.com/questions/1619167/textarea-that-can-do-syntax-highlighting-on-the-fly

**Comment by wwwtyro** [comment]
That's exactly what I was thinking! :+1: Great, I'll do number 2 then. ;)

**Comment by wwwtyro** [comment]
https://github.com/philogb/philogl/pull/45
